### ISSUE TITLE
CMake: please give an example of how to use the lib

### ISSUE THREAD

**Issue by ObiWahn** [iresearch-toolkit/iresearch#106]
After cloning and installing all sub-modules I would expect the following to work:

```
project(sample)
add_executable(sample sample.cpp)
add_subdirectory(iresearch)
target_link_libraries(sample PRIVATE iresearch)
```

This should make all required include directories available to the target sample and build i research in the same configuration as the sample target.

https://github.com/RLovelett/eigen/blob/master/CMakeLists.txt (a lib that is nice to use)

**Comment by vasiliy-arangodb** [comment]
What is the specific issue? What specifically does not work? Please elaborate
