### ISSUE TITLE
cmake fails if ICU_ROOT is used with source

### ISSUE THREAD

**Issue by elfringham** [iresearch-toolkit/iresearch#212]
Needed the following patch to even find the ICU source

diff --git a/cmake/FindICU.cmake b/cmake/FindICU.cmake
index b912c3db..b74043de 100644
--- a/cmake/FindICU.cmake
+++ b/cmake/FindICU.cmake
@@ -70,7 +70,7 @@ find_path(ICU_INCLUDE_DIR
 )
 
 find_path(ICU_SRC_DIR_UCONV
-  ucnv.c
+  ucnv.cpp
   PATHS ${ICU_SEARCH_SRC_PATHS}
   PATH_SUFFIXES common
   NO_DEFAULT_PATH # make sure we don't accidentally pick up a different version

The with ICU_ROOT pointing to a source directory for ICU, cmake fails with

-- IPO_ENABLED: False
-- NOT using gprof output for iresearch
Boost_SHARED_sharedRT_VERSION: 106600
Boost_SHARED_sharedRT_LIBRARIES: /usr/lib64/libboost_locale.so/usr/lib64/libboost_system.so/usr/lib64/libboost_thread.so-lpthread/usr/lib64/libboost_chrono.so/usr/lib64/libboost_date_time.so/usr/lib64/libboost_atomic.so
Boost_SHARED_sharedRT_LOCALE_LIBRARY_DEBUG: /usr/lib64/libboost_locale.so
Boost_SHARED_sharedRT_LOCALE_LIBRARY_RELEASE: /usr/lib64/libboost_locale.so
Boost_SHARED_sharedRT_REGEX_LIBRARY_DEBUG: 
Boost_SHARED_sharedRT_REGEX_LIBRARY_RELEASE: 
Boost_SHARED_sharedRT_SYSTEM_LIBRARY_DEBUG: /usr/lib64/libboost_system.so
Boost_SHARED_sharedRT_SYSTEM_LIBRARY_RELEASE: /usr/lib64/libboost_system.so
Boost_SHARED_sharedRT_THREAD_LIBRARY_DEBUG: /usr/lib64/libboost_thread.so
Boost_SHARED_sharedRT_THREAD_LIBRARY_RELEASE: /usr/lib64/libboost_thread.so
Boost_SHARED_sharedRT_LIB_RESOURCES: /usr/lib64/libboost_locale.so/usr/lib64/libboost_locale.so.1.66.0/usr/lib64/libboost_system.so/usr/lib64/libboost_system.so.1.66.0/usr/lib64/libboost_thread.so/usr/lib64/libboost_thread.so.1.66.0/usr/lib64/libboost_chrono.so/usr/lib64/libboost_chrono.so.1.66.0/usr/lib64/libboost_date_time.so/usr/lib64/libboost_date_time.so.1.66.0/usr/lib64/libboost_atomic.so/usr/lib64/libboost_atomic.so.1.66.0
Boost_SHARED_staticRT_VERSION: 106600
Boost_SHARED_staticRT_LIBRARIES: /usr/lib64/libboost_locale.so/usr/lib64/libboost_system.so/usr/lib64/libboost_thread.so-lpthread/usr/lib64/libboost_chrono.so/usr/lib64/libboost_date_time.so/usr/lib64/libboost_atomic.so
Boost_SHARED_staticRT_LOCALE_LIBRARY_DEBUG: /usr/lib64/libboost_locale.so
Boost_SHARED_staticRT_LOCALE_LIBRARY_RELEASE: /usr/lib64/libboost_locale.so
Boost_SHARED_staticRT_REGEX_LIBRARY_DEBUG: 
Boost_SHARED_staticRT_REGEX_LIBRARY_RELEASE: 
Boost_SHARED_staticRT_SYSTEM_LIBRARY_DEBUG: /usr/lib64/libboost_system.so
Boost_SHARED_staticRT_SYSTEM_LIBRARY_RELEASE: /usr/lib64/libboost_system.so
Boost_SHARED_staticRT_THREAD_LIBRARY_DEBUG: /usr/lib64/libboost_thread.so
Boost_SHARED_staticRT_THREAD_LIBRARY_RELEASE: /usr/lib64/libboost_thread.so
Boost_SHARED_staticRT_LIB_RESOURCES: 
Boost_STATIC_sharedRT_VERSION: 106600
Boost_STATIC_sharedRT_LIBRARIES: /usr/lib64/libboost_locale.so/usr/lib64/libboost_system.so/usr/lib64/libboost_thread.so-lpthread/usr/lib64/libboost_chrono.so/usr/lib64/libboost_date_time.so/usr/lib64/libboost_atomic.so
Boost_STATIC_sharedRT_LOCALE_LIBRARY_DEBUG: Boost_LOCALE_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_sharedRT_LOCALE_LIBRARY_RELEASE: Boost_LOCALE_LIBRARY_RELEASE-NOTFOUND
Boost_STATIC_sharedRT_REGEX_LIBRARY_DEBUG: 
Boost_STATIC_sharedRT_REGEX_LIBRARY_RELEASE: 
Boost_STATIC_sharedRT_SYSTEM_LIBRARY_DEBUG: Boost_SYSTEM_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_sharedRT_SYSTEM_LIBRARY_RELEASE: Boost_SYSTEM_LIBRARY_RELEASE-NOTFOUND
Boost_STATIC_sharedRT_THREAD_LIBRARY_DEBUG: Boost_THREAD_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_sharedRT_THREAD_LIBRARY_RELEASE: Boost_THREAD_LIBRARY_RELEASE-NOTFOUND
Boost_STATIC_staticRT_VERSION: 106600
Boost_STATIC_staticRT_LIBRARIES: /usr/lib64/libboost_locale.so/usr/lib64/libboost_system.so/usr/lib64/libboost_thread.so-lpthread/usr/lib64/libboost_chrono.so/usr/lib64/libboost_date_time.so/usr/lib64/libboost_atomic.so
Boost_STATIC_staticRT_LOCALE_LIBRARY_DEBUG: Boost_LOCALE_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_staticRT_LOCALE_LIBRARY_RELEASE: Boost_LOCALE_LIBRARY_RELEASE-NOTFOUND
Boost_STATIC_staticRT_REGEX_LIBRARY_DEBUG: 
Boost_STATIC_staticRT_REGEX_LIBRARY_RELEASE: 
Boost_STATIC_staticRT_SYSTEM_LIBRARY_DEBUG: Boost_SYSTEM_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_staticRT_SYSTEM_LIBRARY_RELEASE: Boost_SYSTEM_LIBRARY_RELEASE-NOTFOUND
Boost_STATIC_staticRT_THREAD_LIBRARY_DEBUG: Boost_THREAD_LIBRARY_DEBUG-NOTFOUND
Boost_STATIC_staticRT_THREAD_LIBRARY_RELEASE: Boost_THREAD_LIBRARY_RELEASE-NOTFOUND
-- Could NOT find BFD (missing: BFD_INCLUDE_DIR BFD_SHARED_LIBS BFD_STATIC_LIBS BFD_INCLUDE_DIR_ANSIDECL BFD_INCLUDE_DIR_BFD BFD_SHARED_LIB BFD_STATIC_LIB BFD_STATIC_LIB_IBERTY BFD_STATIC_LIB_Z) 
BFD_INCLUDE_DIR: 
BFD_LIBRARY_DIR: 
BFD_SHARED_LIBS: 
BFD_STATIC_LIBS: 
BFD_SHARED_LIB_RESOURCES: 
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (Perl) does
  not match the name of the calling package (Snowball).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPerl.cmake:82 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  external/snowball/CMakeLists.txt:17 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_SHARED_LIBS Unwind_STATIC_LIBS UNWIND_SHARED_LIBRARY_CORE UNWIND_STATIC_LIBRARY_CORE UNWIND_SHARED_LIBRARY_PLATFORM UNWIND_STATIC_LIBRARY_PLATFORM) 
Unwind_INCLUDE_DIR: Unwind_INCLUDE_DIR-NOTFOUND
Unwind_LIBRARY_DIR: 
Unwind_SHARED_LIBS: 
Unwind_STATIC_LIBS: 
Unwind_SHARED_LIB_RESOURCES: 
LZMA static library not found. Required if during linking the following errors are seen: undefined reference to `lzma_...
-- Configuring done
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-shared>

  No target "icudata-shared"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

CMake Error at core/CMakeLists.txt:435 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-shared>

  No target "icudata-shared"

CMake Error at core/CMakeLists.txt:435 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icui18n-shared>

  No target "icui18n-shared"

CMake Error at core/CMakeLists.txt:435 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icuuc-shared>

  No target "icuuc-shared"

CMake Error at core/CMakeLists.txt:449 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

CMake Error at core/CMakeLists.txt:449 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icui18n-static>

  No target "icui18n-static"

CMake Error at core/CMakeLists.txt:449 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:icuuc-static>

  No target "icuuc-static"

CMake Error at core/CMakeLists.txt:597 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-shared>

  No target "icudata-shared"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

CMake Error at core/CMakeLists.txt:597 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

CMake Error at core/CMakeLists.txt:597 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:icudata-static>

  No target "icudata-static"

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by elfringham** [comment]
You may also want this

diff --git a/CMakeLists.txt b/CMakeLists.txt
index ddff19fe..25f129a0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,5 +1,7 @@
 cmake_minimum_required(VERSION 3.8.2 FATAL_ERROR)
 
+cmake_policy(SET CMP0074 NEW)
+
 ################################################################################
 ### set required standard version
 ################################################################################

**Comment by MBkkt** [comment]
https://github.com/iresearch-toolkit/iresearch/blob/master/cmake/FindICU.cmake#L131
