### ISSUE TITLE
Fails to build with gcc-7 and gcc-8 with assertion failure

### ISSUE THREAD

**Issue by elfringham** [iresearch-toolkit/iresearch#222]
The commit
c8479bc592 - fixes a compile warning when using `-Wsuggest-override`
now results in the Travis CI checks failing when built on gcc-7 or gcc-8 with the following assertion failure

/home/travis/build/iresearch-toolkit/iresearch/core/index/index_meta.hpp:118:3: error: static assertion failed
   static_assert(std::is_nothrow_move_assignable_v<index_segment_t>);

**Comment by elfringham** [comment]
Ah, sorry, I see the Travis CI checks were not enabled prior to that, so the build failure is probably not related to that commit.

**Comment by gnusi** [comment]
Sorry, we don't support gcc-7/gcc-8 anymore.
