### ISSUE TITLE
How to Disable SIMDCOMP Compilation on other Architectures

### ISSUE THREAD

**Issue by Jingwiw** [iresearch-toolkit/iresearch#517]
How can I disable the compilation of SIMDCOMP while building on other Architectures like riscv64? It seems that using -DUSE_SIMDCOMP=OFF in my project does not prevent the compilation of SIMDCOMP.

**Comment by MBkkt** [comment]
I think you need to patch our cmake.
In general just remove it, it should be unused if IRESEARCH_SSE2 not defined
https://github.com/iresearch-toolkit/iresearch/blob/master/core/shared.hpp#L113

**Comment by MBkkt** [comment]
Anyway PR welcome, https://github.com/iresearch-toolkit/iresearch/blob/master/cmake/OptimizeForArchitectureLocal.cmake#L10

**Comment by gnusi** [comment]
Project is going to be archived.
