### ISSUE TITLE
What's the semantic of doc id?

### ISSUE THREAD

**Issue by yingfeng** [iresearch-toolkit/iresearch#575]
It seems doc id is only maintained within each segment.  I added logs within `index-search.cpp` and found that for each query, the doc ids got from each segment will duplicate.  Then how to guarantee the real top K docs from multiple segments, or have I misunderstood something ?

**Comment by yingfeng** [comment]
This is how lucene define the document id:
```
The numbers stored in each segment are unique only within the segment, and must be converted before they can be used in a larger context. The standard technique is to allocate each segment a range of values, based on the range of numbers used in that segment. To convert a document number from a segment to an external value, the segment's base document number is added. To convert an external value back to a segment-specific value, the segment is identified by the range that the external value is in, and the segment's base value is subtracted. For example two five document segments might be combined, so that the first segment has a base value of zero, and the second of five. Document three from the second segment would have an external value of eight.
```
It means there exist an external value for each document number, which is actually the internal doc id for each segment plus the segment's base value. 

However, I've not seen similar logic within iresearch. And I could only see that for each segment, the base value is 1, therefore, I did not find the so called "external value" for each doc id.

**Comment by MBkkt** [comment]
It's part of arangodb document

**Comment by MBkkt** [comment]
https://github.com/arangodb/arangodb/blob/devel/arangod/IResearch/IResearchDataStore.cpp#L303

**Comment by yingfeng** [comment]
> https://github.com/arangodb/arangodb/blob/devel/arangod/IResearch/IResearchDataStore.cpp#L303

Thank you.  I notice that a primary key is defined within arangodb document. However, this primary key is not used during search, the search logic is: 

```
DirectoryReader reader;
irs::filter::prepared::ptr filter = prepareFilter(...);
for(; auto& segment : reader){
  //perform query within each segment.
  auto docs = filter->execute(...);
  const irs::document* doc = irs::get<irs::document>(*docs);
  while(docs->next()) {
    docid_t doc_id = doc->value;  // internal segment id
    // scoring for each doc_id
    ...
    push_heap(make_pair(score,doc_id));
  }
}
```

According to the above search logic, duplicate doc_id would be inserted into heap.

**Comment by MBkkt** [comment]
We are using reader-offset + doc_id https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/IResearchViewExecutor.tpp#L1381

**Comment by MBkkt** [comment]
index-search is test only code, what you point is kind of bug, but it's not really important, because commonly benchmarks for wiki dataset running on fully compacted segment, also chance to have same score and same doc_id quite unrealistic

**Comment by yingfeng** [comment]
Got it, thanks for your explain
