### ISSUE TITLE
Benchmark results compared to lucene

### ISSUE THREAD

**Issue by yingfeng** [iresearch-toolkit/iresearch#83]
Have any benchmarks been made between iresearch and lucene using the benchmark tool until `utils`?  
In additionm, it seems the raw document data has not been stored, so after top N document ids have been got, corresponding document content could not be got without another key-value store ?

**Comment by gnusi** [comment]
@yingfeng yes, we measured performance compared to lucene 3-4 months ago with the benchmark tool. Some queries were up to 30x times faster, other 3-4x times slower, but we plan to beat them by the 1.0 release.

@yingfeng you can decide the amount of data you would like to store in the index, we have columnstore for that purpose. If you like you can store the raw document inside, and after getting top N document ids, you can access the data you've put.
