### ISSUE TITLE
Supporting real time search

### ISSUE THREAD

**Issue by yingfeng** [iresearch-toolkit/iresearch#84]
It seems the index building is performed on a batch basis where each batch will generate an index segment, as a result, frequent index merging will occur, such mechanism is not friendly for real time search unless there exsits an in-memory segment, is there any plan to introduce such an in-memory segment, which is composed of a lock-loss data structure and corresponding write ahead log for corruption recovery ?

**Comment by gnusi** [comment]
Yes, we plan to implement that soon. Probably by 1.0 release which is coming later this fall.

@yingfeng Do you use IResearch somehow in your projects?

**Comment by yingfeng** [comment]
Yeah, I am considering an experimental project to build a real "elastic" search system which is composed of both an efficient ir toolkit and a reliable global distributed log with consistency guaranteed.

**Comment by yingfeng** [comment]
What's the status of this feature(real time indexing) right now?

**Comment by gnusi** [comment]
@yingfeng unfortunately it's still not yet there

**Comment by gnusi** [comment]
Project is going to be archived.
